#!/usr/bin/env bun
/**
 * select-candidates — shortlist library skills using governed index metadata.
 *
 * This is a selection aid, not the final reuse decision. It deterministically
 * enforces quality-state eligibility and ranks by controlled tag overlap.
 *
 * Usage:
 *   node select-candidates.ts --use-case debugging,research --limit 10
 *   node select-candidates.ts --characteristic evidence-first --portability high
 *   node select-candidates.ts --use-case api-design --include-unverified
 *
 * Requires index.json version 2+ generated by scripts/build-index.ts.
 */

import { parseArgs } from "node:util";
import { existsSync, readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "..", "..");
const INDEX = join(ROOT, "index.json");
const ELIGIBLE = new Set(["trusted-baseline", "verified", "validated"]);
const BLOCKED = new Set(["stale", "rejected", "retired"]);

const { values } = parseArgs({
  options: {
    "use-case": { type: "string" },
    lifecycle: { type: "string" },
    characteristic: { type: "string" },
    authority: { type: "string" },
    portability: { type: "string" },
    "include-unverified": { type: "boolean", default: false },
    limit: { type: "string", default: "12" },
    json: { type: "boolean", default: false },
    help: { type: "boolean", default: false },
  },
});

if (values.help) {
  console.log(`select-candidates — governed bootstrap shortlist\n\n` +
    `Usage: node select-candidates.ts [filters] [--include-unverified] [--limit 12] [--json]\n\n` +
    `Filters:\n` +
    `  --use-case <comma-list>\n` +
    `  --lifecycle <comma-list>\n` +
    `  --characteristic <comma-list>\n` +
    `  --authority <comma-list>\n` +
    `  --portability <comma-list>\n`);
  process.exit(0);
}

if (!existsSync(INDEX)) {
  console.error("BLOCKED: index.json is missing. Run node scripts/build-index.ts in a fully materialized repository.");
  process.exit(2);
}

const index = JSON.parse(readFileSync(INDEX, "utf8"));
if ((index.version ?? 0) < 2) {
  console.error("BLOCKED: index.json predates governed selection metadata. Regenerate with node scripts/build-index.ts.");
  process.exit(2);
}

function csv(value: string | undefined): string[] {
  return (value ?? "").split(",").map((v) => v.trim()).filter(Boolean);
}

const requested = {
  use_case: csv(values["use-case"]),
  lifecycle: csv(values.lifecycle),
  characteristic: csv(values.characteristic),
  authority: csv(values.authority),
  portability: csv(values.portability),
};

interface Candidate {
  name: string;
  sourceId: string;
  sourceLabel: string;
  sourceRole: string;
  skillFile: string;
  description: string;
  verificationStatus: string;
  validationStatus: string;
  characterized: boolean;
  tags: Record<string, string[]>;
  score: number;
  matched: string[];
  selectionUse: "eligible-unchanged" | "design-evidence-only";
}

function overlap(actual: string[] = [], wanted: string[] = []): string[] {
  if (!wanted.length) return [];
  const set = new Set(actual);
  return wanted.filter((v) => set.has(v));
}

function scoreCandidate(c: Candidate): Candidate {
  const matched: string[] = [];
  let score = 0;
  for (const [dimension, wanted] of Object.entries(requested)) {
    const hits = overlap(c.tags[dimension] ?? [], wanted);
    for (const hit of hits) matched.push(`${dimension}:${hit}`);
    score += hits.length * 10;
    if (wanted.length && hits.length === 0) score -= 3;
  }
  if (c.verificationStatus === "validated") score += 4;
  else if (c.verificationStatus === "verified") score += 3;
  else if (c.verificationStatus === "trusted-baseline") score += 2;
  else if (c.verificationStatus === "unverified") score -= 8;
  c.score = score;
  c.matched = matched;
  return c;
}

function candidateFrom(source: any, skill: any): Candidate | null {
  const q = skill.quality ?? {};
  const status = q.verificationStatus ?? "unverified";
  if (BLOCKED.has(status)) return null;
  if (!ELIGIBLE.has(status) && !(values["include-unverified"] && status === "unverified")) return null;

  return scoreCandidate({
    name: skill.name,
    sourceId: source.sourceId,
    sourceLabel: source.label,
    sourceRole: source.sourceRole,
    skillFile: skill.skillFile,
    description: skill.description ?? "",
    verificationStatus: status,
    validationStatus: q.validationStatus ?? "not-run",
    characterized: q.characterized ?? false,
    tags: q.tags ?? {},
    score: 0,
    matched: [],
    selectionUse: ELIGIBLE.has(status) ? "eligible-unchanged" : "design-evidence-only",
  });
}

const candidates: Candidate[] = [];
for (const source of Object.values(index.vendor ?? {}) as any[]) {
  if (Array.isArray(source.skills)) {
    for (const skill of source.skills) {
      const c = candidateFrom(source, skill);
      if (c) candidates.push(c);
    }
  }
  for (const plugin of source.plugins ?? []) {
    for (const skill of plugin.skills ?? []) {
      const c = candidateFrom(source, skill);
      if (c) candidates.push(c);
    }
  }
}

candidates.sort((a, b) => b.score - a.score || a.name.localeCompare(b.name) || a.sourceId.localeCompare(b.sourceId));
const limit = Math.max(1, Number.parseInt(values.limit ?? "12", 10) || 12);
const selected = candidates.slice(0, limit);

if (values.json) {
  console.log(JSON.stringify({ requested, count: selected.length, candidates: selected }, null, 2));
  process.exit(0);
}

if (!selected.length) {
  console.log("No governed candidates matched the current eligibility rules. Consider custom creation, broader criteria, or explicit unverified design-evidence review.");
  process.exit(0);
}

for (const c of selected) {
  console.log(`${c.score.toString().padStart(3)}  ${c.name}  [${c.verificationStatus}]  ${c.sourceLabel}`);
  console.log(`     use=${c.selectionUse} matched=${c.matched.join(", ") || "none"}`);
  console.log(`     ${c.skillFile}`);
}
